import { Inter } from "next/font/google";
import "./reset.css";
import "./globals.css";

import { AppBar } from "@/components/AppBar";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <AppBar />
        <div className="layout bg-white-300">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
